### PR TITLE
feat!: remove propTypes in production builds

### PR DESCRIPTION
**Pull request by wincent**
Core commit here is: https://github.com/liferay/liferay-npm-tools/commit/1b2e3cc1936ad6e99de494cf001ed7a36947db6a

But seeing as I had to update the dependency graph, I updated a number of other outdated dependencies too.

### CODE REVIEW

**Comment by wincent** [comment]
CI is green, so I am going to cut a non-`latest` test release so that I can test this thoroughly in liferay-portal.

**Comment by wincent** [comment]
Test versions are:

- https://www.npmjs.com/package/liferay-npm-bundler-preset-liferay-dev/v/4.2.2-beta.1
- https://www.npmjs.com/package/liferay-npm-scripts/v/18.0.0-beta.1

**Comment by wincent** [comment]
Here's a sample with a `NODE_ENV` of "development" in liferay-portal. I added some `console.log()` statements as markers:

Untitled_Basic_Web_Content_-_Liferay

Note the `propTypes` in between the two statements. Now, running with a `NODE_ENV` of "production", we get this:

Untitled_Basic_Web_Content_-_Liferay

**Comment by jbalsas** [comment]
spread_love

**Comment by wincent** [comment]
So, JS tests are green in liferay-portal, formatting/linting works (will need to apply autofixes etc) so I think this is good to merge.

**Pull request merged**
