### PR TITLE
chore(scripts): send build output to "build" instead of "classes" (#272)

### PR DESCRIPTION
**Pull request by wincent**
As per: https://github.com/liferay/liferay-npm-tools/issues/272

### CODE REVIEW

**Comment by wincent** [comment]
Just a draft because there are probably a couple of places where we will want to update the path in the liferay-js-toolkit as well.

**Comment by wincent** [comment]
PR to liferay-js-toolkit is here: https://github.com/liferay/liferay-js-toolkit/pull/424

**Comment by wincent** [comment]
By way of testing this, here is an example run against frontend-js-web:

- Here's what the "build" and "classes" directories looked like (when running `yarn build`) before this PR: https://gist.github.com/wincent/3d2bdfcbbdbcb44314407043ffaed0f8
- Here's what they look like after the PR: https://gist.github.com/wincent/2853acdffed24b3214fd53fd5383b347
- Here's what they look like once you configure the bridge generator: https://gist.github.com/wincent/25c6236d2fd99174852fe8692c4383c9
- Here's what they look like once you adjust the webpack config: https://gist.github.com/wincent/00264e7ed49700b5be54a7d5e4db9542
- And here's what they look like once you configure the bundler: https://gist.github.com/wincent/87ec5c29a2755de8e2c1589ec0b8e1bb

Changes to bridge config:

```
diff --git a/modules/apps/frontend-js/frontend-js-web/.npmbridgerc b/modules/apps/frontend-js/frontend-js-web/.npmbridgerc
index 83d767a718be..f42d496c402d 100644
--- a/modules/apps/frontend-js/frontend-js-web/.npmbridgerc
+++ b/modules/apps/frontend-js/frontend-js-web/.npmbridgerc
@@ -9,8 +9,8 @@
 			"to": "bridge/frontend-js-web/$1"
 		},
 		"file-globs": "liferay/**/*.js",
-		"input": "classes/META-INF/resources",
-		"output": "classes/META-INF/resources/bridge/frontend-js-web",
+		"input": "build/node/packageRunBuild/resources",
+		"output": "build/node/packageRunBuild/resources/bridge/frontend-js-web",
 		"src-mod-name-mapper": {
 			"from": "(.*)\\.js$",
 			"to": "frontend-js-web/$1"
```

Changes to webpack config:

```
diff --git a/modules/apps/frontend-js/frontend-js-web/webpack.config.js b/modules/apps/frontend-js/frontend-js-web/webpack.config.js
index 4c70b91a424a..a0a9edd43dd2 100644
--- a/modules/apps/frontend-js/frontend-js-web/webpack.config.js
+++ b/modules/apps/frontend-js/frontend-js-web/webpack.config.js
@@ -35,7 +35,7 @@ module.exports = {
 	output: {
 		filename: 'global.bundle.js',
 		libraryTarget: 'window',
-		path: path.resolve('./classes/META-INF/resources/liferay/'),
+		path: path.resolve('./build/node/packageRunBuild/resources/liferay/'),
 		publicPath: PUBLIC_PATH
 	}
 };
```

Changes to bundler config:

```
diff --git a/modules/apps/frontend-js/frontend-js-web/.npmbundlerrc b/modules/apps/frontend-js/frontend-js-web/.npmbundlerrc
index 9b8fb822f489..b83a5f4229e6 100644
--- a/modules/apps/frontend-js/frontend-js-web/.npmbundlerrc
+++ b/modules/apps/frontend-js/frontend-js-web/.npmbundlerrc
@@ -6,5 +6,6 @@
 		"**/*.js",
 		"!**/*.es.js",
 		"!**/*.soy.js"
-	]
+	],
+	"output": "build/node/packageRunBuild/resources"
 }
\ No newline at end of file
```

**Comment by wincent** [comment]
Based on Slack chat, this seems worth taking a risk on:

- Before change in that test, 187 files in "classes" directory
- After, 187 files in "build"
- We think content changes are unlikely
- Just have to change config in 95 modules that use liferay-npm-scripts, and hope for the best... (sadly we can't know it works end-to-end without cutting a release and sending a PR to Peter Shin for integration).

**Comment by jbalsas** [comment]
> Just have to change config in 95 modules that use liferay-npm-scripts, and hope for the best... (sadly we can't know it works end-to-end without cutting a release and sending a PR to Peter Shin for integration).

Isn't the change in `liferay-npm-scripts` mostly covered by this change?

**Comment by wincent** [comment]
> Isn't the change in `liferay-npm-scripts` mostly covered by this change?

I think I have to test each module (95 in liferay-portal that use `liferay-npm-scripts build`) to be sure that:

- They are using the preset.
- If they have an `.npmbundlerrc`, that they are not overriding the "output" field (unlikely).
- If they have a webpack config (there are only a few of these); their paths point at the right place.
- If they have a bridge rc file, that it has the right config.

At least in the case of the first module I tested (above), I had to make changes in three places to get it to put the output in the right place. "frontend-js-web" doesn't use the dev preset, for example, so it needed an explicit change to the bundler rc file.

**Comment by wincent** [comment]
do it live

**Comment by wincent** [comment]
PRs using this sent over to Peter Shin:

- https://github.com/petershin/liferay-portal/pull/719
- https://github.com/petershin/liferay-portal-ee/pull/172

**Pull request merged**
