### PR TITLE
feat: apply custom Liferay-specific formatting in Prettier post-processing step

### PR DESCRIPTION
**Pull request by wincent**
~WIP, draft only, but~ the approach looks like it will work.

Exploring this so that we don't have to patch or fork Prettier itself. I have a demo patch for that, but it is disappointing, because it requires modifying a private function that is > 3k lines long.

```diff
From b8fc8ff43df2e61902822016e75f780df4b76218 Mon Sep 17 00:00:00 2001
From: Greg Hurrell <greg.hurrell@liferay.com>
Date: Thu, 28 Nov 2019 15:25:01 +0100
Subject: [PATCH] "feat": customize Prettier

Example diff:

    @@ -43,11 +43,12 @@
      }

      function h(x: number): string {
        if (x) {
          return "foo";
    -   } else {
    +   }
    +   else {
          throw new Error();
        }
      }
---
 src/language-js/printer-estree.js | 1 +
 1 file changed, 1 insertion(+)

diff --git a/src/language-js/printer-estree.js b/src/language-js/printer-estree.js
index 49b4552e..1cfaaffb 100644
--- a/src/language-js/printer-estree.js
+++ b/src/language-js/printer-estree.js
@@ -1833,6 +1833,7 @@ function printPathNoParens(path, options, print, args) {
         }
 
         parts.push(
+          hardline,
           "else",
           group(
             adjustClause(
-- 
2.20.1
```

### CODE REVIEW

**Comment by jbalsas** [comment]
Semi-Nice! 👍

**Comment by wincent** [comment]
Moved this out of draft status but we shouldn't merge it yet because we need to run the change past Brian first.

**Comment by wincent** [comment]
Test release (beta): https://github.com/liferay/liferay-npm-tools/pull/311

**Comment by wincent** [comment]
Sent sample change to Brian here: https://github.com/brianchandotcom/liferay-portal/pull/81484

Note that `git grep -l '} else' -- '*.js'` reports that there are still a few files that didn't get modified, which is likely due to some syntax inside them that will require special tweaking of the ESLint config. About half a dozen when you ignore the ones that we shouldn't need to touch:

```
apps/fragment/fragment-collection-contributor/fragment-collection-contributor-basic-component/src/main/resources/com/liferay/fragment/collection/contributor/basic/component/dependencies/slider/index.js
apps/fragment/fragment-collection-contributor/fragment-collection-contributor-basic-component/src/main/resources/com/liferay/fragment/collection/contributor/basic/component/dependencies/video/index.js
apps/fragment/fragment-collection-contributor/fragment-collection-contributor-featured-content/src/main/resources/com/liferay/fragment/collection/contributor/featured/content/dependencies/banner-slider/index.js
apps/opensocial/opensocial-portlet/docroot/WEB-INF/src/features/rpc/rpc.js
apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/criteria_builder/CriteriaBuilder.es.js
apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/criteria_builder/CriteriaGroup.es.js
apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/criteria_builder/CriteriaRow.es.js
apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/criteria_builder/DropZone.es.js
apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/inputs/DateInput.es.js
apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/inputs/DateTimeInput.es.js
apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/inputs/SelectEntityInput.es.js
apps/segments/segments-web/src/main/resources/META-INF/resources/js/components/segment_edit/SegmentEdit.es.js
dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/src/main/resources/META-INF/resources/js/components/list/Item.es.js
dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/src/main/resources/META-INF/resources/js/components/list/List.es.js
dxp/apps/portal-search-tuning/portal-search-tuning-rankings-web/src/main/resources/META-INF/resources/js/components/list/SearchBar.es.js
sdk/project-templates/project-templates-npm-react-portlet/src/main/resources/archetype-resources/src/main/resources/META-INF/resources/lib/index.es.js
test/jenkins-results-parser/src/main/resources/com/liferay/jenkins/results/parser/dependencies/jenkins_report.js
yarn-1.13.0.js
```

I'll look into the cause on Monday (although it might also be an itch that I have to scratch over the weekend).

**Comment by wincent** [comment]
Fixed to cover those 11 files: https://github.com/wincent/liferay-portal/pull/97 (not updating the PR on Brian's fork because if I do the bot will just close it and he won't see it).

**Comment by bryceosterhaus** [comment]
This PR makes me sad. I have very real fears that when we open this door, we start to just become csf and the java source formatter all over again, making incremental changes based on arbitrary "taste" of how code looks. The real benefit of not making custom formatting changes is that we can just rely on prettier and not have to use our time on custom formatting preference. My fear is that we end up just wasting time due to arbitrary syntactical preference.

_me walking around the db office_
Alt Text

**Comment by wincent** [comment]
@bryceosterhaus: Please send selfie of you wearing that sign, next to Brian. 😂

In all seriousness, I understand and share your concerns, which is why this isn't merged and why [the PR I sent to Brian](https://github.com/brianchandotcom/liferay-portal/pull/81484) is labeled "DO NOT MERGE"/"for discussion only". Brian values consistency, which is why Liferay has long had so much source formatting infra (almost all of it built before Prettier existed; in an alternate universe in which Prettier came out in the year 2000, we might well be using it everywhere, even for Java). The value of consistency is obvious, but the question to settle is, does *cross-language consistency* matter enough to justify the kind of change implemented in this PR. Obviously, every step away from the Prettier standard that we take dilutes the benefit we get from participating in that ecosystem.

We're going to talk with Brian about it on our next weekly sync (Wednesday) and obviously he'll make the final call. When Chema reached the agreement with Brian about adding Prettier near the beginning of 2019, it was contingent on us preparing something like this before the end of the year. Since then, we've had time to see the value that participating in the Prettier ecosystem has brought us; so we'll check in and see where we land on the whole cross-language consistency issue.

**Comment by bryceosterhaus** [comment]
Yeah I totally understand the argument and history behind it. And I am sure most of us in infra all agree its best to not add additional formatting. I am just making sure I speak up and overly express my concern so that it can be communicated to Brian. The more we express our point of view and if we can get consensus on the FE side, I think it helps our argument since we are the ones who will actually run into issues and not Brian. If he can see that we are really opposed to adding tweaks, and that its more harm than gain for us on a day to day basis, I think he may be fine letting us keep it how it is.

Sidenote, do you have any idea how this would integrate with built in prettier/eslint support in vscode? would this require us to run the format manually?

**Comment by wincent** [comment]
@bryceosterhaus:

> Sidenote, do you have any idea how this would integrate with built in prettier/eslint support in vscode? would this require us to run the format manually?

This is actually one of the major reasons why *not* to do something like this PR, because I don't think there is a nice way to do this. We either end up with a terrible hack, a fork, build our own (for N editors!) or have to switch our mindset and always run formatting manually before submitting. I actually always do the format-before-submit thing because I am an odd one who doesn't want my editor making edits to my files, but I know that there are many users of VSCode here and one of the things they love about it is this kind of integration.

**Comment by wincent** [comment]
Just to reflect here the discussion with Brian: I think he gets the core trade-off here (cross-language consistency within Liferay vs the value of leveraging a standard ecosystem). He's going to think about it, give Chema one last chance to talk him out of it 😂 when he gets back from vacation, and make a decision after GA1 in January. He also notes that we can change our mind about this at any time and it's just re-formatting.

**Comment by wincent** [comment]
Closing this for now. Brian and Chema discussed it and there is no need to rush something like this. They'll revisit the topic when Brian is in the Madrid office (in February, I think).

**Comment by wincent** [comment]
Rebased and resent: https://github.com/liferay/liferay-npm-tools/pull/365

**Comment by bryceosterhaus** [comment]
sad

**Pull request closed without merging**
