### PR TITLE
feat(scripts): add support for optional chaining and nullish coalescing

### PR DESCRIPTION
**Pull request by wincent**
Both are at stage 4:

- https://github.com/tc39/proposal-optional-chaining
- https://github.com/tc39/proposal-nullish-coalescing

Test plan: with this PR active in liferay-portal, insert some test JS like this:

```js
console.log(window.x?.thing?.[0] ?? 'fallback');
```

Inspect build folder and see it got transpiled to ES5 (pretty-printed for readability):

```js
var _ref, _window$x, _window$x$thing;

console.log(
  (_ref =
    (_window$x = window.x) === null || _window$x === void 0
      ? void 0
      : (_window$x$thing = _window$x.thing) === null ||
        _window$x$thing === void 0
      ? void 0
      : _window$x$thing[0]) !== null && _ref !== void 0
    ? _ref
    : "fallback"
);
```

Closes: https://github.com/liferay/liferay-npm-tools/issues/450

### CODE REVIEW

**Comment by wincent** [comment]
[Build failure](https://travis-ci.org/github/liferay/liferay-npm-tools/builds/686093628) looks spurious:

```
The command "git clone --single-branch https://github.com/jasongin/nvs $NVS_HOME" failed and exited with 128 during .
```

Worked fine [on Linux here](https://travis-ci.org/github/liferay/liferay-npm-tools/jobs/686093445) and [on Windows here](https://travis-ci.org/github/liferay/liferay-npm-tools/jobs/686093446).

Sadly, looks like our we don't have a "Restart" job button any more; I guess the people managing our access decided it was too much power... 🤷‍♀️

**Comment by izaera** [comment]
@wincent a workaround to re-run the CI is to close & reopen the PR.

**Comment by wincent** [comment]
> @wincent a workaround to re-run the CI is to close & reopen the PR.

I only half believe you. So I am going to try it. 😂

**Comment by izaera** [comment]
LGTM

**Comment by izaera** [comment]
@wincent I inly hilf biliivi yii....

**Comment by wincent** [comment]
Screenshot 2020-05-12 -150631-1e2chPZJ@2x

Hashtag: `#Elegant`

**Pull request merged**
